name: p10_db
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/OnkelTem/p10_db

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.4.6
  args: ^2.5.0
  dotenv: ^4.2.0
  logging: ^1.2.0
  intl: ^0.19.0
  chalkdart: ^2.2.1

dev_dependencies:
  husky: ^0.1.7
  lints: ^4.0.0
  test: ^1.24.0
